### ISSUE TITLE
switch from raw Pod to Deployment

### ISSUE THREAD

**Issue by clkao** [jupyterhub/kubespawner#138]
Currently the singleuser notebooks are simple pod objects, and there are a few benefits for using 1-replica deployment I can think of:

- notebooks can survive through host node loss or pod eviction
- stateless hub: known users are just 0-replica and 1-replica deployments
- stopped server can be seen as paused notebook, as their pod spec persists until explicitly shutdown. So even hub config updates new user image or other settings, users don't get surprises.

**Comment by joelpfaff** [comment]
It may be hard to permanently associate the Pods generated by the DeploymentController with their Persistent Volumes. In case of failure, the recreated pod would come with an empty PV, and that defeats the purpose of using PV at all.
I am wondering if the Hub could not directly rely on [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/).
Then we have the choice between a StatefulSet per Notebook, with a replica of 1, and while simpler to manage in the Hub, it can mean a lot of objects to manage in kube when the number of users grow.
We could also try to rely on a single StatefulSet, allow pods in it per user, and let Kubernetes do the magic.

**Comment by yuvipanda** [comment]
Thanks for the suggestion! I considered using a Deployment / ReplicaSet, and decided against it for the following reasons:

1. Notebooks (and kernels) have in-memory state, so if a pod dies and is restarted elsewhere, it's state is entirely different now! There isn't much we can do about this (until full container snapshotting works and exists anyway), so it's much better to let the user know that this happened. Otherwise, the ipython (or other language kernel) would lose all its state and the user might not know, leading to pretty bad results.
2. The JupyterHub code already tracks running servers, and supports things like multiple servers per user. I think of JupyterHub as a 'controller' for notebook pods.

As for making hub stateless, I don't think we can do that without pretty much rewriting JupyterHub, unfortunately. And even then, I'd probably store state in a ConfigMap or CRD rather than in Deployment objects, primarily due to reason (1). I also think at large number of users (I'm currently running stress tests with upto 50k) putting the state in kubernetes itself is a bad idea for performance reasons, and we should use a database there anyway.

I hope these make sense! This project needs a lot of documentation writing I haven't gotten around to, unfortunately :(

**Comment by yuvipanda** [comment]
@joelpfaff StatefulSets also have the same problem I mentioned about (primarily (1)). Using a single statefulset for *all* users is an intriguing idea, but it's unclear what benefits it'll bring over the current setup. I also don't think it'll survive a very large number of users.

 Also #140 is already implemented, am unsure why statefulsets are needed for that?

**Comment by joelpfaff** [comment]
@yuvipanda thanks for the reply :)
I agree that seeing the hub as a `controller` is a powerful concept, that could manage all the subtleties of  the lifetime of the jupyter pods. But it comes with additional complexity, so I was wondering if relying on StatefulSet would not have simplified the picture (by reusing existing k8s concepts).
After seeing your reply, I agree with you, it does not seem to fit the usecase correctly.

**Comment by abelliae** [comment]
Re (1) isn't that exactly the "Restart kernel" case?

In the current default setup if a pod goes down, nothing happens till the user interacts with the front-end for the first time (after crash) getting some quite unexpected error message. At least, after a failure in local host the user would have the opportunity to restart the kernel, which can't be done on k8s when a server pod dies.

Wouldn't expecting at least an automatic server restart (advertised through the "kernel restart" label) be a better UX? Maybe this can already be configured? Am I missing something?

**Comment by yuvipanda** [comment]
A kernel can die for many reasons, such as it has no memory or a bug. However, when the pod dies, the entire notebook server goes, along with all the kernels, so it's hard to provide any UX there. I do agree our current UX around notebook servers dying is terrible and needs fixing in the Notebook UI - similar to how we have UI for kernels dying.

**Comment by consideRatio** [comment]
Yuvi's initial response is something that I think still make sense.

I think neither a Deployment or replicaset makes sense, because the user sessions won't be "cattle", they will be "pets" - in k8s cattle is things that can be replaced, while pet is things that can't. This is because the things loaded in memory etc won't be retained if a pod shuts down and starts up elsewhere etc.

If we would go with a deployment, we would be forced to set it to 1 replica, to add a pod disruption budget saying user pods should not be allowed to be relocated etc, and when we have done all things we end up with the same functionality as just having a Pod I think.

**Comment by droctothorpe** [comment]
How would you feel about a PR that provided support replicasets but was off by default and toggleable via helm values? The notebook containers are stateful but given that our user's home directories are EFS backed and notebooks are auto-saved, the disruption wouldn't be so bad and it would help automate our rehydrations.

**Comment by consideRatio** [comment]
At this point in time @droctothorpe, it seems like a significant addition of complexity to KubeSpawner, and I have seen very little support for this kind of feature in general until now at least. Due to that, I'm feeling skeptical at the moment.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-amalthea/12208/2
