### ISSUE TITLE
Add support for SpawnerForm that lets you pick which Image to run

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/kubespawner#14]
For feature parity with https://github.com/sveesible/jupyterhub-kubernetes-spawner.

**Comment by elgalu** [comment]
@sveesible would you be willing to back port upstream your customizations to allow `SINGLEUSER_IMAGE` be chosen from a fixed list?

**Comment by elgalu** [comment]
Implementation wise, what I'm thinking now is: instead of having [one single Start My Server](https://github.com/jupyterhub/jupyterhub/blob/e1deecbbfbb38/share/jupyter/hub/templates/home.html#L15) is to iterate over a list and have one button for each image, e.g. Start my {image-name} notebook.

To achieve that I was thinking about adding a new `singleuser_image_spec_list` simil to [singleuser_image_spec](https://github.com/jupyterhub/kubespawner/blob/37558770fc9/kubespawner/spawner.py#L282). It's an idea more aligned to [c.DockerImageChooserSpawner.dockerimages](https://github.com/ryanlovett/imagespawner)

**Comment by keithcallenberg** [comment]
@elgalu I like the idea of `singleuser_image_spec_list` but could it default to displaying as a drop-down? I think many users have more than just a few images, which would make buttons impractical.

FWIW, I've been running something similar to @sveesible 's KubeOptionsSpawner in a team environment for a month now and it has been working great. Some documentation with examples of overloading KubeSpawner might reduce the need to bake these customizations in.

**Comment by elgalu** [comment]
> I've been running something similar to @sveesible

Could you open source it?

**Comment by sveesible** [comment]
mine is using the jupyterhub interface pattern for making a select list to
choose from also letting you customize the env variables before launch

**Comment by jlewi** [comment]
This is what Kubeflow does.
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/jupyterhub_spawner.py

I think we are doing the Jupyterhub interface pattern as @sveesible mentions above.

**Comment by yuvipanda** [comment]
Fixed in #137
