### ISSUE TITLE
Support multiple user servers

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/kubespawner#142]
Hello.
As of today, when one user starts a server, a pod with a name such as `jupyter-<username>` is created. I think it is a good practice to add a kind of sha1/tag in the name to allow multiple deployment. For example, hub has a name such as `hub-66c9fb8db-rd8t9` instead of just `hub` (zero to jupyterhub config).

Being able to use a tag/sha1 in the name might allow the following features:
- start an instance while the previous one is still "pending stop"
- start a second instance (quite useful when https://github.com/jupyterhub/kubespawner/pull/137 will be finished). I guess some work still need to be done on jupyterhub itself, but that could be useful.

**Comment by clkao** [comment]
how about deploying into different namespaces?

**Comment by gsemet** [comment]
Hello. Yes this the current situation, but some cannot easily instantiate a namespace per application, especially for testing. I guess it is the rational behind a majority of helm chart automatically adding the release name in front of each kube artefact. At least admin have the option to deploy n time the same app in the same namespace.

**Comment by consideRatio** [comment]
I interpret what @gsemet is saying as the wish to be able to have multiple user servers running. This is now something that JupyterHub itself can support with named servers.

I think it adds a bit too much complexity if the goal is to only have 1 single user server but be able to manage multiple sessions coming and going etc, especially since some pods will end up with storage that can only be mounted by one pod at the time or similarly.
