### ISSUE TITLE
Ensure multiple PVCs

### ISSUE THREAD

**Issue by petoknm** [jupyterhub/kubespawner#156]
I see that there is a variable `c.KubeSpawner.pvc_name_template` for the PVC name that will be ensured to be created if `c.KubeSpawner.user_storage_pvc_ensure = True`. How can I ensure multiple PVCs are created? Similar problem is with having multiple `c.KubeSpawner.user_storage_capacity` and `c.KubeSpawner.user_storage_class` values. It would be nice to have those set individually per PVC. Is that possible and I just missed something or is that just not implemented?

**Comment by stevenstetzler** [comment]
I'm also wondering if support will be added for automatic provisioning of multiple PVCs. (Or if I've missed this in the documentation.) I am using an NFS-backed volume for notebook home storage, which does not require dynamic provisioning of PVCs (the notebook pod just references an existing one). However, I'd also like to have extra space with faster storage, for example scratch space or a place to install custom code that needs to be accessed quickly instead of over NFS. My current hack is to use the single PVC that the KubeSpawner guarantees and mount it in the notebook under `/scratch` for example instead of `/home/{username}`, but this is limited to only a single volume.

I see from the source for `spawner.py` that the user's PVC is straightforwardly created, could this be extended to a for-loop over a field of the KubeSpawner? Perhaps `c.KubeSpawner.claims_to_provision`? https://github.com/jupyterhub/kubespawner/blob/a945ef01410867b39e0c174d362a8702bbaa15e9/kubespawner/spawner.py#L1665-L1701

**Comment by manics** [comment]
You might be able to do it by sub-classing `Kubespawner` and overriding `start()` to setup your volumes before calling the parent method. You can do this in your config.yaml file, you wouldn't need to build a new Jupyterhub image.

If you try this let us know if it works!

**Comment by consideRatio** [comment]
> How can I ensure multiple PVCs are created?

It is out of scope for KubeSpawner to do this I'd say, closing this issue as stale and in my mind out of scope for kubespawner to implement as a feature

**Comment by jabbera** [comment]
I have the same need!

**Comment by jabbera** [comment]
For anyone interested this seems to work:

```
@gen.coroutine
    def modify_pod(self, spawner: Spawner, pod: V1Pod):
        user = spawner.user.name

        server_claim = next(filter(lambda x: x.name == 'server-storage', pod.spec.volumes))

        claim_name = server_claim.persistent_volume_claim['claimName']
        self.log.info(f"modify pod hook for {user} found claim {claim_name}")

        pvc = V1PersistentVolumeClaim()
        pvc.metadata = V1ObjectMeta()
        pvc.metadata.name = claim_name
        pvc.spec = V1PersistentVolumeClaimSpec()
        pvc.spec.access_modes =  ['ReadWriteOnce']
        pvc.spec.storage_class_name = "scratch-disk"
        pvc.spec.resources = V1ResourceRequirements()
        pvc.spec.resources.requests={"storage": "32Gi"}

        yield exponential_backoff(
                partial(
                    spawner._make_create_pvc_request, pvc, spawner.k8s_api_request_timeout
                ),
                f'for user: {user} Could not create PVC {claim_name}',
                # Each req should be given k8s_api_request_timeout seconds.
                timeout=spawner.k8s_api_request_retry_timeout,
            )

        return pod
```
