### ISSUE TITLE
Does KubeSpawner verify the traitlets needlessly late?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#241]
After #236, more fields are verified on spawn before being sent to the k8s API server to trigger the creation of a Pod.

This can be improved further by verifying traitlet fields when they are set instead, it would allow for KubeSpawner to fail on faulty setup super early - in general on hub startup where most of the configuration of the spawner is done.

Hmmm... or wait a second... Perhaps this is only done first when the Spawner is created, and since every used has an individual Spawner, it will be during the first spawn anyhow?

**Comment by minrk** [comment]
I'm not sure how much earlier it can be. Traitlets are verified on access, which ensures that they are verified in the correct order, and avoids unnecessary validation of unused values. Since the first Spawner is created ~immediately before it is launched, verification on assignment should only occur a fraction of a second earlier for anything validated during spawn.

Let's back up a bit: what practical problem is currently caused by how and when trait verification occurs, and what would be an improvement on that?

**Comment by consideRatio** [comment]
Hmmm hmmm hmmm good questions leads to better thinking for me.

I hoped to see a way for developers of z2jh using KubeSpawner to quickly, *on hub startup*, realize if the c.KubeSpawner configuration was valid without having to wait for a user to fail spawn. It would had been an awesome timesaver for me before, but with https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/846 it will not be as important.

We could do something like this though, but the drawback is that perhaps it is known and accepted that some configuration will fail unless complemented with additional settings, dunno...

```python
mock_spawner_to_validate_conf = KubeSpawner(config=c, _mock=True)
mock_spawner_to_validate_conf.get_pod_manifest()
```

**Comment by consideRatio** [comment]
Let's not try optimize this as it isn't clear how we would go about it and I cannot come up with a good idea that doesn't introduce too much complexity.
