### ISSUE TITLE
Free form input for configuration pre spawn (specify docker image)

### ISSUE THREAD

**Issue by mrocklin** [jupyterhub/kubespawner#317]
I'm curious about allowing a user to run their own entirely custom Docker image.  On the splash screen they would be presented with a dialog into which they would paste an address to a docker image.  Looking [through issues here](https://github.com/jupyterhub/kubespawner/issues/108) I found references to [ProfileSpawner](https://github.com/jupyterhub/wrapspawner), which seems to get me part of the way there. 

Is there a standard way to do this today?

If not, what is the right approach?  Take the same approach as ProfileSpawner  and write a bit of code to handle the user interaction on the front end and then pass back to something like KubeSpawner?

**Comment by h4gen** [comment]
I am also interested in this. I was wondering if the expansion of the `{username}` e.g. used for volumes could be expanded to the pod image. This would at least make it possible for admins to point to an image with a prefix e.g. `org/hub_notebook_{username}` and users could push their images in the respective registry.  I am doing this right now with the 'modify_pod_hook'.

At first I write a certain key word as image in the profile list 
```
kubespawner_override:
    image_spec: USER
```
And then I look for this key word and replace it with the proper image name:
```
username = spawner.user.name
if pod.spec.containers[0].image == 'USER':
    img_str = 'idalab/hub_user_' + username
    pod.spec.containers[0].image = img_str
```

This is easily possible with the current `profile_list` capabilities. The backside is that the users need to have access to one certain container registry and they can't define a tag.

If the expansion of `{username}` for the image is interesting I would make a PR.

**Comment by dkipping** [comment]
I also think that this sounds like a great idea for the extendability and flexibility of the jupyterhub.

I am just wondering, if that does not go into the direction that [binderhub](https://github.com/jupyterhub/binderhub) is trying to tackle?

I mean with binderhub you basically have a jupyterhub and then the possibility to launch whatever github repository on there, as the repository is built to a docker image, right?

Or is binder limited to jupyter environments, but you want the user to be able to break out of jupyter environments (e.g. launching just an ubuntu image with a terminal running on the hub)?

Just trying to understand the differentiations here. :)

**Comment by h4gen** [comment]
@dkipping This is correct, but this approach is limited. For example: Our organization uses Jupyterhub with pangeo. This is a certain configuration which also allows distributed computations via dask (Thanks to @mrocklin). This requires setting up node pools and configuring the k8s cluster. Long story short: At least in our case binderhub is great for getting a fast notebook environment (e.g. for educational purposes) but not for providing a rich tool chain for professionals in a stable environment (at least as far as I understand binderhub).

**Comment by dkipping** [comment]
I see, thanks for the clarification!
If binderhub more or less limits the user to notebook environments (even from custom git repositories) but does not enable for simple launch of other non-jupyter environments, then allowing to specify such images as you suggested would probably be a huge help for many people facing similar scenarios as you do.

I think the way to go now is still the 'profile_list', from which the user can choose.
Even though https://github.com/jupyterhub/kubespawner/pull/301 (which to my knowledge was the last change to user parameters for the spawn) states that you can provide custom overrides for the spawner.

So I guess the most intuitive way to achieve this with custom code (or a PR to be) would be to handle an image field from the 'user_options' in the same way as the 'kubespawner_override.items()' are handled in ['_load_profile'](https://github.com/jupyterhub/kubespawner/pull/301/files#diff-3082573191d96b79e2ec71986d4ef3e2R1886), so taking the image field in the ['load_user_options()'](https://github.com/jupyterhub/kubespawner/pull/301/files#diff-3082573191d96b79e2ec71986d4ef3e2R1896) for the consequent override instead of just the profile_list.

**Comment by betatim** [comment]
You can launch what ever environment you want with BinderHub. For example the pangeo binder instance gives you access to dask worker pools etc.

> but not for providing a rich tool chain for professionals in a stable environment 

I'm not sure exactly what @h4gen is missing or feels is missing. Also it is unclear what a "rich tool chain for professionals" is meant to imply/mean ;)

BinderHub is "just" a new frontend for a JupyterHub that takes care of all the work around building an image on demand and then asking JupyterHub to launch that specific image for that specific user.

A good discussion on this topic is https://discourse.jupyter.org/t/how-do-you-properly-pass-arguments-to-jupyterhub-spawner-on-rest-api-call/688/2.

There is a demo of a [BinderHub with persistent storage and auth](https://github.com/jupyterhub/binderhub/issues/794) as well.

---

Hi there 👋!

Can we move this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

Thanks!

**Comment by h4gen** [comment]
@betatim Thanks for the information. Tbh, I was a bit confused about the difference between binder and binderhub. This looks great and it looks like I have to do a bit more reading... What I basically mean with rich environment are really huge images. I am still a bit sceptical tbh. I think repo2docker is a great tool for creating containers but its yet another tool a user has to learn. So, @topic I don't see why there shouldn't be the possibility for users to change their image, which they have created locally, without being forced using repo2docker schema and learning a new tool. Forcing users to transfer their docker images with stuff like gpu drivers, config,... to repo2docker, seems a bit hard to me.

**Comment by consideRatio** [comment]
Closing this in favor of #279 which is about supporting free form text configuration by the user of various configuration fields. I would say, this kind of change is unsustainable to implement in Spawner subclasses, and should instead be implemented in the Spawner base class itself.
