### ISSUE TITLE
Utilize pyflakes in CI

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#358]
We realized the benefit of having something like pyflakes to catch basic python errors in https://github.com/jupyterhub/kubespawner/pull/357.

This issue could be closed by updating the CI system to run a pyflake on our python code, and fail on basic errors.

**Comment by minrk** [comment]
Yes! One point though, `flake8` is a better runner for pyflakes because it allows selecting when to apply the checks, `# noqa` comments, etc. which is useful in CI because pyflakes can complain on valid code and has no configuration.

See the [jupyterhub flake8 configuration](https://github.com/jupyterhub/jupyterhub/blob/master/.flake8) for an example.
