### ISSUE TITLE
Documentation Missing

### ISSUE THREAD

**Issue by Robert-Carver** [jupyterhub/kubespawner#370]
The documentation pages for:
- "KubeSpawner"
- "Objects"
- "Reflectors"
- "Custom Traitlets"
- "Utilities" 
Have mysteriously vanished.

**Comment by consideRatio** [comment]
Thanks for reporting this @Robert-Carver! :heart:

Here is a link to verify that they have indeed vanished: https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html

Here is the latest read the docs build, which is passing: https://readthedocs.org/projects/jupyterhub-kubespawner/builds/9980877/

I recall this happened before, I don't remember why... But, I bet it relates to the issues with kubernetes==11.0.01b as has been disturbing other things as well.

**Comment by consideRatio** [comment]
# AHA!

It is because read the docs generate this documentation by first installing kubespawner, but unlike `pip install -r requirements.txt`, installing with `python setup.py install` will install the requirements with pre-releases included: https://github.com/pypa/setuptools/issues/855

This makes the install succeed, but when we use it kubespawner will fail as it installed a broken pre-release. What we need to do is ensure we don't install the pre-releases. One way to go, is to first run `pip install -r requirements.txt`. I'll try that.
