### ISSUE TITLE
Should kubespawner be using await instead of yield for exponential_backoff?

### ISSUE THREAD

**Issue by chancez** [jupyterhub/kubespawner#428]
I'm trying to debug an issue (#427) and noticed that the timeout exceptions don't seem to be properly propagated up. I noticed kubespawner calls `exponential_backoff` from `jupyterhub.utils` using `yield` like so:

https://github.com/jupyterhub/kubespawner/blob/d2ee6019d7935c903ebf0715d64534012e450778/kubespawner/spawner.py#L1857-L1861

But I see it being used with `await` in jupyterhub: https://github.com/jupyterhub/jupyterhub/blob/66cb2c0f3ef17b41d4e334d6b00fc91489edbca3/jupyterhub/spawner.py#L1191-L1196

I'm not as familiar with async in python, but it seems like kubespawner might be incorrectly using this function. Further reading suggests, that `yield from` is the correct usage for doing this prior to `await` existing, which also indicates `yield` may not be the correct approach?

**Comment by yuvipanda** [comment]
Since that function is still a [tornado coroutine](https://www.tornadoweb.org/en/stable/guide/coroutines.html), I *think* yield might be doing the right thing? However, we should switch to async / await syntax anyway, and I don't understand enough about the error propagation differences between yield with `@gen.coroutine` vs await with `async def`. 

So I *think* to use `await` here, you'd need to convert the entire function into an `async def`, and mostly just replace `yield` with `await`?

**Comment by chancez** [comment]
Ah gotcha. Yeah, that makes sense. I missed that we were in a coroutine so I think that was the missing piece.

**Comment by consideRatio** [comment]
By assuming Python 3.6+, we have been able to merge #444 which replaced a lot of `yeild` statements that were used as a workaround to accomplish async/await related stuff.

Here is the code statement you refer to after #444 @chancez.

https://github.com/jupyterhub/kubespawner/blob/44d638b7c63576b7f88e82e6073de3f2ee2c4116/kubespawner/spawner.py#L1932-L1947

Since it is done, I assume this issue can be closed as resolved. Thank you for your work on this project @chancez :heart:!
