### ISSUE TITLE
singleuser PVC deletion when the helm chart is uninstalled

### ISSUE THREAD

**Issue by lupaang** [jupyterhub/kubespawner#432]
Hey guys, first of all,  thank you for maintaining a great project.

I'm using jupyterhub with helm chart and when I spawn a single user notebook by jupyterhub, I usually mount a volume(ex. EBS, EFS etc..) with notebook.

However when I delete the hub, since the spawned notebook is not managed by helm chart - no labels, no annotations related to the chart - so the mounted PVC remains released while the hub is gone. There's extraLabel option on singleuser storage but usually labels are created with helper template, we cannot refer those labels within values.yaml. 

I'm not sure this spec is related to kubespawner or not, but I want to suggest kubespawner to pass the helm related labels to singleuser spawned resources like notebook mounted storage, or notebook itself.

Thanks in advance.

### Proposed change
Delete every notebook-mounted PVC when a jupyterhub is uninstalled.

**Comment by consideRatio** [comment]
You can add some labels using `common_labels` to be able to target the created PVC resources that you want to cleanup, or using the `storage_extra_labels` to get them only on the PVC resource.

This issue is a bit related to #446 as well, which suggests that we should remove storage as part of deleting JupyterHub users through the JupyterHub UI. I'll close this as a mix of duplicate / resolved by common_labels etc, but we also want to make the JupyterHub Helm chart configure KubeSpawner to set some common labels such as app.kubernetes.io/instance etc in the future, but that is something for the JupyterHub helm chart to do rather than KubeSpawner.
