### ISSUE TITLE
Set fsGroupChangePolicy in Kubespawner

### ISSUE THREAD

**Issue by cyrilcros** [jupyterhub/kubespawner#478]
### Proposed change

One of the new beta feature in kubernetes 1.20 is the new `fsGroupChangePolicy` in a `securityContext`. See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods That's a beta feature in 1.20, not alpha as the old text says.
It avoids the lengthy process of "chown'ing" a volume which can be very slow when images have lot of files (ie tensorflow etc...) - see https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1252 This is especially true if the docker-stacks images people use all have the right permissions already set.

It would be nice to make this option a default if it works with version below 1.20...

That could also alternatively done if the securityContext configuration was exposed - ie https://github.com/jupyterhub/kubespawner/issues/454 was implemented.

It is present in the kubernetes Python client library v1.18 and up since it was in alpha then.

**Comment by consideRatio** [comment]
`fsGroupChangePolicy` will be made configurable as part of the `pod_security_context` introduced in #480, so that part is a duplicate of #454.

__Let `fsGroupChangePolicy` default to `"OnRootMismatch"`?__

I don't think KubeSpawner should introduce a default value for such a significant change. This would influence all containers of the pod, and while I think it could be a nice default, it would be going against the k8s default which is something that I think is very problematic.

If we deviate from k8s defaults in KubeSpawner regarding this:

1. We would probably help a group of KubeSpawner users by providing a higher performance default
2. We would also introduce an opinionated choice that few will be aware of, which would lead to an unexpected outcome that can cause these users spend significant time debugging etc.

Due to this, I'm quite strongly opinionated against letting KubeSpawner become opinionated about this, less opinionated about the JupyterHub Helm chart becoming opinionated about it, but think the way to go is to provide documentation in z2jh.jupyter.org associated with the JupyterHub Helm chart regarding this as a choice.

**Comment by elferherrera** [comment]
Is `fsGroupChangePolicy` configurable? I cannot find the setting modify this value

**Comment by consideRatio** [comment]
This was not implemented i think, use pod_security_context

**Comment by elferherrera** [comment]
is there an example of `pod_security_context` usage?

**Comment by elferherrera** [comment]
Sorry. I think I found it here
https://github.com/jupyterhub/kubespawner/blob/96867c5bbc67c3ccd73ab62ba11d811825deb0ee/tests/test_objects.py#L462

**Comment by wiegerthefarmer** [comment]
I don't seem to be able to set the fsGroupChangePolicy through the pod_security_context in the KubeSpawner....

like....
c.KubeSpawner.pod_security_context.update({'fsGroupChangePolicy': 'OnRootMismatch'})

Doesn't seem to do anything....

**Comment by wiegerthefarmer** [comment]
> Sorry. I think I found it here
> 
> https://github.com/jupyterhub/kubespawner/blob/96867c5bbc67c3ccd73ab62ba11d811825deb0ee/tests/test_objects.py#L462

@elferherrera did you end up solving this?

**Comment by elferherrera** [comment]
Yeap. Just changed the pod security context
