### ISSUE TITLE
c.Kubespawner.modify_pod_hook does not support co-routines

### ISSUE THREAD

**Issue by stv0g** [jupyterhub/kubespawner#490]
### Bug description

I am facing an issue when providing a co-routine to `c.Kubespawner.modify_pod_hook`.

The Tornado docs for `gen.maybe_future()` say that `maybe_future` can only handle Futures and no other yieldable objects.

Does this mean, we can pass coros as a hook function?
I mean a coro which as been declared via `async def ...`

#### Expected behaviour

`c.Kubespawner.modify_pod_hook` should support co-routines.

#### Actual behaviour

`c.Kubespawner.modify_pod_hook` only supports normal functions or futures.

If passed a co-routine, I will pass the co-routine into the Kubernetes client which fails.

### How to reproduce

1. Define a co-routine via the `async def `syntax:

```python
import asyncio

async def my_pod_modify_hook(spawner):
     await asyncio.sleep(1)
     return

c.Kubespawner.modify_pod_hook = my_pod_modify_hook
```

### Your personal set up

A pretty standard Z2JH setup (master)

**Comment by consideRatio** [comment]
@stv0g can you try make this bug report (?) clearer by providing:
- a way to reproduce the faulty behavior
- a description of the faulty behavior that follows
- a description of what you expected

**Comment by stv0g** [comment]
@consideRatio I updated the issue description.

**Comment by consideRatio** [comment]
Thanks @stv0g!

Not being an expert about this, this statement leaves me with open questions.

> #### Expected behaviour
> `c.Kubespawner.modify_pod_hook` should support co-routines.

Do you mean that the modify_pod_hook should be allowed to be a function with `async` for example?

I'm also a bit uncertain about the example. I assume what my_pod_modify_hook actually should do, is supposed to return the modification rather than a future.

```diff
import asyncio

async def my_pod_modify_hook(spawner):
-    return asyncio.sleep(1)
+    return await asyncio.sleep(1)

c.Kubespawner.modify_pod_hook = my_pod_modify_hook
```

**Comment by stv0g** [comment]
> Do you mean that the modify_pod_hook should be allowed to be a function with async for example?

Exactly. The hook function of JupyterHub support this now already for some time by replacing Tornados gen.maybe_future:
https://github.com/jupyterhub/jupyterhub/blob/0ca2ef68f04b59648dd9ad4ce85454c24f533f5d/jupyterhub/utils.py#L493

I propose that Kubespawner uses here the same implementation as JupyterHub.

> I'm also a bit uncertain about the example. I assume what my_pod_modify_hook actually should do, is supposed to return the modification rather than a future.

You are right. This is an error in my example.

**Comment by consideRatio** [comment]
Ah okay excellent now I understand and agree with this being something to address!

I'll go ahead and frame this as a enhancement request rather than a bug =)

Could you also help indicate what kind of error you get when you set `c.Kubespawner.modify_pod_hook = my_async_func` ?

**Comment by stv0g** [comment]
> I'm not confident what should be fixed, but perhaps KubeSpawner should stop using gen.maybe_future and instead rely on from jupyterhub.utils import maybe_future? Do you think this makes sense? I'm just guessing.

Yes, I would support this. I could also submit a PR :)

**Comment by minrk** [comment]
> KubeSpawner should stop using gen.maybe_future and instead rely on from jupyterhub.utils import maybe_future

Yes! That's the right thing to do.

If you want, though, I don't think kubespawner needs to be as fully general as jupyterhub's own implementation, which aims for maximum compatibility to ensure it didn't break anything when we made the big asyncio transition. If you are a little more strict about what things may return, you can even optimize a bit by avoiding the unnecessary `await` if it's not awaitable:

```python
result = some_function()
if inspect.isawaitable(result):
    result  = await result
```

The only case that won't handle is `concurrent.futures` which is not really important to handle yourself because it's only asking the author of the function to add `asyncio.wrap_future()` on the end before returning it to kubespawner, if they happen to be using thread pools (tornado's `@run_in_executor` helper already does this). The only reason jupyterhub handles this is tornado's maybe_future handled it before and we wanted to make sure nothing broke.

Or, alternately, for APIs that should always return None:

```python
result = some_function()
if result is not None:
    await result
```

which is an even cheaper check than `isawaitable()`:

- `x is None` ~ 30ns
- `inspect.isawaitable(x)` ~ 700ns
- `jupyterhub.utils.maybe_future(x)` ~ 2µs (not counting extra await for non-async callables)

(all these timescales are negligible when adding kubernetes API requests to the mix)
