### ISSUE TITLE
Expose Kubernetes client configuration options

### ISSUE THREAD

**Issue by kafonek** [jupyterhub/kubespawner#492]
### Proposed change
Expose a way to inject configuration options for the `kubespawner.KubeSpawner.api` object.  Right now it appears to be instantiated without passing in args or kwargs (`self.api = shared_client('CoreV1Api')`).  

### Alternative options
Some configuration options can be set via environment variables, but others cannot.  For instance, `kubernetes.client.Configuration.get_default_copy().ssl_ca_cert`

### Who would use this feature?
Kubernetes clusters that use custom CA certs may be misconfigured such that the ca-certs provided to service accounts (`/var/run/secrets/kubernetes.io/serviceaccounts/ca.crt` inside the Hub pod) do not work with the Kubernetes API server.  When Kubespawner attempts to initialize and list pods in the namespace, it raises a `CERTIFICATE_VERIFY_FAILED` error.  

See https://discourse.jupyter.org/t/enabling-jh-to-use-an-additional-ca-cert-when-calling-private-k8s-api/6662 and discussions in Jupyerhub Gitter between me and @consideRatio on Mar 1 / Mar 2 2021.

It is worth noting that there's probably a cluster administration solution to this problem.  I do not know what needs to change on the cluster configuration side to provision working `ca.crt` files to the serviceaccount / accompany secrets.  Either way, I think offering config options in Kubespawner and zero-to-jupyterhub `config.yaml` is worthwhile.

### (Optional): Suggest a solution
I defer to @yuvipanda @consideRatio on how to implement this.  From a user perspective, I would like to be able to mount my actual CA certs into the Pod and then tell KubeSpawner to use them either via ENV variables or as a config option.  Imagine I have a `ca-certs` Secret in my namespace with a `ca.crt` file that includes the k8s API ca's, and I'm deploying jupyterhub with the zero-to-jupyterhub-k8s helm chart.

```
# config.yaml
hub:
  extraVolumes:
    - name: ca-crt
      secret:
        secretName: ca-certs
  extraVolumeMounts:
    - name: ca-crt
      mountPath: /etc/pki/certs/ca-certificate.crt
      subPath: ca.crt
  # NEW SYNTAX (?)
  kubeSpawner:
    ssl_ca_cert: /etc/pki/certs/ca-certificate.crt
  # ALTERNATIVELY
  extraEnv:
    KUBESPAWNER_CA_CERT: /etc/pki/certs/ca-certificate.crt
```

```
# kubespanwer.clients.py
import kubernetes.client

def shared_client(ClientType, *args, **kwargs):
    # caching stuff in here, not included for the sake of brevity
    # kubernetes.config.load_incluster_config() already called prior to invoking this function
    if 'KUBESPAWNER_CA_CERT' in os.environ:
        conf = kubernetes.client.Configuration.get_default_copy()
        conf.ssl_ca_cert = os.environ['KUBESPAWNER_CA_CERT']
        kubernetes.client.Configuration.set_default(conf)
    Client = getattr(kubernetes.client, ClientType)
    client = Client(*args, **kwargs)
    return client    
```

**Comment by consideRatio** [comment]
It seems like even though we can pass "client configuration", it seem to override anything about `cert_filename` or `ssl_ca_cert`, which seem to make the idea of passing a client configuration with such info bound to fail. 

So, it seems that to support this configuration we must be very explicit along the lines you suggest rather than allowing for a general passthrough of configuration.

```
In [5]: kubernetes.config.load_incluster_config?

Signature:
kubernetes.config.load_incluster_config(
    client_configuration=None,
    try_refresh_token=True,
)
```

Hmmm...

**Comment by consideRatio** [comment]
Since this seems to require a change to KubeSpawner dedicated to solving this specific issue, as we can't pass a general configuration, I'd like to not go for this change without better understanding why it is needed.

In the following example for using the kubernetes-client/python code to communicate with a "remote cluster", and then they set the ssl_ca_cert explicitly.

But, when you are a pod within the cluster, I'm a bit confused - is the hub trying to communicate with another cluster? If not, why does it get setup with the wrong ca info through the serviceaccount? Is the k8s service account associated secret outdated and need to be recreated to have the latest CA info?

https://github.com/kubernetes-client/python/blob/f17076f0e12bd894877825906864b42f25756f0c/examples/remote_cluster.py#L15-L17

My suggested path forward:
- [ ] To try acquire a better understanding of what we are working around. This probably involves communication with a k8s cluster admin to figure out as this typically would work without issue, so what makes this cluster need a separate ca.crt.
- [ ] Consider `kubectl edit hub-token-dxf8r` as an option, modifying the content of the ca.crt key within that service account.

**Comment by kafonek** [comment]
@consideRatio I looked more closely at the `ca.crt` being provisioned to the serviceaccount by the k8s api.  Our `default` serviceaccount / `default-token` secret and the `hub` sa/secret have the same `ca.crt`.  It turns out the `ca.crt` is an intermediate CA.  I do not know enough about how CA checking works to say whether there's an environment variable or flag that would change Python's behavior and let it accept an intermediate CA without having the root CA as well?

```
[mkafonek@mbs10a z2jh]$ kubectl describe secret/ca-certs
Name:         ca-certs
Namespace:    mbs-jupyterhub
Labels:       app=cacerts
              chart=cacerts-2020.0.1
              heritage=Tiller
              release=ns-mbs-jupyterhub
Annotations:  helm.fluxcd.io/antecedent: gob:helmrelease/ns-mbs-jupyterhub

Type:  Opaque

Data
====
bundle.pem:                                11292 bytes
ca.crt:                                    11292 bytes
dev-AD01-CA.pem:                           1237 bytes
intermediate-us-east-1-kubernetes-ca.pem:  2065 bytes
us-east-1-ca.pem:                          1915 bytes
us-east-1-full.pem:                        3993 bytes
us-east-1-intermediate.pem:                2078 bytes

[mkafonek@mbs10a z2jh]$ kubectl describe secret hub-token-vgb2zName:         hub-token-vgb2z
Namespace:    mbs-jupyterhub
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: hub
              kubernetes.io/service-account.uid: d79010ed-9979-479d-9d5d-1f78e4cd7073

Type:  kubernetes.io/service-account-token

Data
====
namespace:  14 bytes
token:      <token>
ca.crt:     2065 bytes
```

To answer your three questions directly - 
  * Restarting the service gets the same (intermediate) ca.crt every time
  * I have not tried manually editing the token but that wouldn't be a good long-term solution for our deployment
  * I think we better understand what's happening now

**Comment by kafonek** [comment]
@consideRatio we're still trying to find clear documentation about whether provisioning the intermediate ca to a service token is by design or not.  None-the-less, I created a fork of kubespawner.py and an image that just derives from `jupyterhub/k8s-hub:0.11.1` that installs the local fork.  The only change I made was in `kubespawner.clients.py` --

```python
if client is None:
        # Inject configs for non-standard ca-cert location (issue 492)
        if "KUBESPAWNER_CA_CERT" in os.environ:
            conf = kubernetes.client.Configuration.get_default_copy()
            conf.ssl_ca_cert = os.environ["KUBESPAWNER_CA_CERT"]
            kubernetes.client.Configuration.set_default(conf)

        Client = getattr(kubernetes.client, ClientType)
        client = Client(*args, **kwargs)
        # cache weakref so that clients can be garbage collected
        _client_cache[cache_key] = weakref.ref(client)
    return client
```

That does fix the issue, I'm open to suggestions on different/better places to place that configuration override.

**Comment by consideRatio** [comment]
@kafonek thanks for the exploration and verification that the specific change would solve your issue correctly!

I'm not at ease about this change though. I'm thinking that all software communicating with the k8s api-server from inside a container would need to be adjusted, not just KubeSpawner in the hub pod. In the JupyterHub Helm chart, there is for example also the `user-scheduler` and the `hook-image-awaiter` pods that would need a configuration update as they also speak with the k8s api-server. All in all, I expect this to become a common issue for other helm charts being installed.

After a while I assume there will be some software that just can't be updated properly to accept a custom cert to speak the k8s api-server, so then what would be done?

I feel the need for more understanding about this issue and the decision to go for configuring all k8s api-server clients to use a custom cert on the side apart from the k8s ServiceAccount associated k8s Secret.

In my mind, if this was truly required and couldn't be addressed while configuring the k8s cluster setup, I would suggest that the k8s cluster admin would create a _MutatingWebhook_ that updated all k8s Secrets representing a k8s ServiceAccount token and ca.crt with the correct k8s Certificate. By doing so, the issue would be resolved for all pods in one go.

**Comment by kafonek** [comment]
@consideRatio I understand your perspective.  I'll keep an eye out for similar issues in those pods as I get z2jh moving forward on our cluster.  I think there's two basic questions you're asking here -

1. Should this issue be closed and the burden be placed onto the cluster administrator to provision appropriate `ca.crt` files in the serviceaccount token secret or solve it with options such as the MutatingWebhook?  Is the kubespawner project willing to support non-standard or misconfigured clusters? **(caveat: I'm still not sure it's a misconfiguration for clusters with custom CA and intermediate CA's to provision the intermediate CA's)** I think Kubespawner should support this customization option, personally.

2. Should this issue be handled outside of Kubespawner code to be more generalizable?  I don't want to speak for developers of any other projects, but I imagine the devil's advocate answer is that if we were using `kubernetes.py` directly then we would have the tooling available to customize the options, as posted earlier in this thread or examples such as https://stackoverflow.com/questions/48351308/how-to-specify-ca-bundle-in-kubernetes-python-client.

Kubespawner.py as a tool for interacting with the k8s API doesn't give that customization option.  It calls  `kubernetes.config.load_incluster_config()` and there's no way to inject configuration for `.ssl_ca_cert` (and some other config options as you note) without forking the project.

**Comment by manics** [comment]
I also share @consideRatio concerns, I feel like this sort of configuration is too low level to support directly as a Kubespawner configurable. However I'd be less opposed to allow overriding the `shared_client` function through sub-classing, which has the added benefit of supporting more general K8S client configuration if necessary. It's also easier to specify the requirements of the function ("give me a working Kubernetes client") than to deal with the details of defining supporting configuration parameters.

The downside is would require a significant refactoring of the code to pass the client from KubeSpawner through to the methods using the client- but maybe this would be needed anyway if a configuration parameter was used in order to pass it from KubeSpawner to the function?

**Comment by kafonek** [comment]
@manics I'm happy with any solution that is less hacky then us having to create a docker image that derives from `jupyterhub/k8s-hub` and copies in new files like a fork of kubespawner or code to monkeypatch `kubernetes.client`.  If that solution is somewhere besides the `shared_client` function, great.  

I agree in spirit that what I want is, "give me a working Kubernetes client".  

tagging in other users that I think have seen this issue in their own clusters: @geeklisted @drewsimmons @metric-chicken

**Comment by consideRatio** [comment]
## Pathway to accepting this configuration

### Also support configuring `host`

This is a tweaked example of what @kafonek suggested that also configures the `host` which likely goes hand in hand with the `ssl_ca_cert` config in many situations.

```python
def shared_client(ClientType, *args, **kwargs):
    # ...
    if client is None:
        # configure the k8s client's network access to the k8s api-server
        if "KUBESPAWNER_K8S_SSL_CA_CERT" in os.environ:
            conf = kubernetes.client.Configuration.get_default_copy()
            conf.ssl_ca_cert = os.environ["KUBESPAWNER_K8S_SSL_CA_CERT"]
            kubernetes.client.Configuration.set_default(conf)
        if "KUBESPAWNER_K8S_HOST" in os.environ:
            conf = kubernetes.client.Configuration.get_default_copy()
            conf.ssl_ca_cert = os.environ["KUBESPAWNER_K8S_HOST"]
            kubernetes.client.Configuration.set_default(conf)

        Client = getattr(kubernetes.client, ClientType)
        client = Client(*args, **kwargs)
        # cache weakref so that clients can be garbage collected
        _client_cache[cache_key] = weakref.ref(client)
    return client
```

### Configure with traitlets instead of env vars

I think I'd favor configuration of kubespawner using the typical configuration options (traitlets) instead of 
through environment variables.

### Documentation about it

I'd like there to be a clear documentation with regards to if and when users should expect and want to configure this, and if by doing so they may end up with similar issues. I assume the need to configure this will lead to issues with many other k8s workloads deployed in a k8s cluster and would like to have that discussed.

### What I'd like to avoid

I'll describe what I'd like to avoid, and what I think is needed for this to be avoided, is some research to verify this is really the needed and there is no better way.

What I'd like to avoid in short is that users of KubeSpawners are led to believe that something make sense to do and we put in effort to support that path, but then realize it just isn't sustainable and learns how to solve it properly in another way.

So in practice I want to avoid that we first let KubeSpawner, the `user-scheduler`, and the `hook-image-awaiter` configure this which requires documentation and maintenance only to later learn there was a better way both for end users of the JupyterHub Helm chart and the maintainers of the Helm chart, and that the users of these config options stopped looking for that solution instead because we provided this path to resolve it.

For my mind to be more at ease, I'd like as much as possible validation that this really is what makes sense to do generally. Perhaps other Helm charts have done it like this and clarified it was no way around it that made more sense?

**Comment by kafonek** [comment]
https://github.com/rook/rook/issues/3122#issuecomment-498320421 details a workaround using `PodPreset` for the intermediate CA problem if you can administer the cluster.  We're talking to our cluster admins about enabling the PodPreset admission controller.  Our config would in theory look like - 

```
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: fix-ca-bundle
  namespace: mbs-jupyterhub
spec:
  selector:
    matchLabels:
      app: jupyterhub
      component: hub
  volumeMounts:
     mountPath: /run/secrets/kubernetes.io/serviceaccount/ca.crt
      name: ca-certs
      subPath: ca.crt
  volumes:
    - name: ca-certs
      configMap:
        name:  ca-certs
```

Still looking at a PR for you @consideRatio for cases when the cluster admin cannot or will not add the PodPreset controller.

**Comment by consideRatio** [comment]
Ah, this sounds like a promising idea but since the ca.crt is already a mounted file, I think you will error if you make a PodPreset inject that another volume/volumeMount mounting the same file. But that can be avoided by disabling automatic mounting of the token I guess.

Hmmm, but then the token needs to be manually mounted also... Yikes!

Excellent detective work tracking that reference down @kafonek. For me, a key issue of doing such work myself is that I don't yet understand the "intermediate CA" parts. Do you know of a place I can learn about that kind of setup?

**Comment by kafonek** [comment]
@consideRatio https://medium.com/@oleg.pershin/kubernetes-from-scratch-certificates-53a1a16b5f03 covered the setup process well, although it didn't touch on the errors we're seeing with the Kubernetes Python client failing on cert verify.  The discussion within Openshift when they ran into this issue was also worth reading through, https://bugzilla.redhat.com/show_bug.cgi?id=1654558.  If I understand their solution right, it was a cluster administration solution.

Going back to our CA stack, think of the root CA as being for the network as a whole.  It signs intermediate certs that are used for various application deployments, some in Kubernetes, some not.  The team responsible for the root CA might be different than the team responsible for the Kubernetes cluster, and thus give them an intermediate CA to work with instead of the root CA key directly.  Here's what a snipped-out version of the subject/issuer pairings look like for our stack right now -

```
[mkafonek@mbs10a ~]$ kubectl describe secrets/ca-certs
Name:         ca-certs
...
Data
====
intermediate-us-east-1-kubernetes-ca.pem:  2065 bytes
us-east-1-ca.pem:                          1915 bytes
us-east-1-intermediate.pem:                2078 bytes

[mkafonek@mbs10a ~]$ kubectl get secrets ca-certs -o jsonpath='{.data.us-east-1-ca\.pem}' | base64 -d | openssl x509   -subject -issuer -noout
subject= /C=US/O=stack-bootstrap/CN=stack-bootstrap CA
issuer= /C=US/O=stack-bootstrap/CN=stack-bootstrap CA

[mkafonek@mbs10a ~]$ kubectl get secrets ca-certs -o jsonpath='{.data.us-east-1-intermediate\.pem}' | base64 -d | openssl x509   -subject -issuer -noout
subject= /C=US/O=stack-bootstrap/CN=stack-bootstrap Intermediate CA
issuer= /C=US/O=stack-bootstrap/CN=stack-bootstrap CA

[mkafonek@mbs10a ~]$ kubectl get secrets ca-certs -o jsonpath='{.data.intermediate-us-east-1-kubernetes-ca\.pem}' | base64 -d | openssl x509   -subject -issuer -noout
subject= /C=US/O=stack-bootstrap/CN=us-east-1-kubernetes-ca
issuer= /C=US/O=stack-bootstrap/CN=stack-bootstrap CA
``
