### ISSUE TITLE
start.sh usermod and kubespawner mount volumes in home

### ISSUE THREAD

**Issue by djangoliv** [jupyterhub/kubespawner#574]
I am using base-notebook

In jupyterhub_config.py I add a volume:

```
c.KubeSpawner.volume_mounts = [
    {
        'name': 'common',
        'mountPath': '/home/{username}/my_dir',
    },
]

```
So kubspawner creates the '/home/{username}' directory before running start.sh
In start.sh: After the `usermod` that changes `jovyan` to `{username}` there is a copy of `/home/jovyan` to `/home/{username}` but only if `/home/{username}` does not yet exist.
But with the volume, the home of `{username}` already exists and the copy does not happen.

Maybe we can force the copy with an environment variable (`$COPY_HOME`) and not test if the home already exists.

Any suggestions are welcome.

Regards

**Comment by manics** [comment]
It sounds like this needs to be managed in your container, not KubeSpawner:
https://github.com/jupyter/docker-stacks/blob/69ddfa810e503342713cd5fac76fbc767ebb5c8b/base-notebook/start.sh#L67-L201

**Comment by consideRatio** [comment]
This is a discussion related to jupyter/docker-stacks. My understanding is that you discuss the following feature summarized.

1. You have ensured there is a `/home/{username}/some_dir` ahead of time
2. As part of the `start.sh` script of jupyter/docker-stacks runs, you have made it switch from a `jovyan` user to `{username}`. As part of this script running, you want to be able to make `start.sh` change its default behavior when the `{username}` home folderexists. You want either to replace the `{username}` folder if it exists, or in some way merge content from `jovyan` home folder to the existing `{username}` folder.

I would overall say that this is a quite uncommon action, and could easily lead to loss of data if misunderstood by someone. Due to that, I'm not so happy about the idea of supporting a feature like that - if I understood it correctly.

**Comment by consideRatio** [comment]
Oh... I couldn't transfer this issue to jupyter/docker-stacks as it was outside the organization. Anyhow, that is where this belongs. You could perhaps copy paste things from this to there if you want to raise it for discussion? Please if so, also include my response.

**Comment by benz0li** [comment]
@djangoliv If you mounted `/home/{username}` instead of `/home/{username}/some_dir` your _use case_ would be the same as https://github.com/jupyter/docker-stacks/issues/1478.
