### ISSUE TITLE
Single-user pods and other associated resources should have ownerReferences set to the jupyter-hub

### ISSUE THREAD

**Issue by TomHellier** [jupyterhub/kubespawner#628]
### Proposed change
I use argocd to manage kubernetes clusters, and therefore rarely look at the kubernetes dashboard.

I have recently started using jupyter notebooks using zero-to-jupyterhub running inside a kubernetes cluster. I was expecting to be able to see the single-user pods using the Argocd ui.

I believe the ownerReference of the single-user pods should be the Hub deployment. I suspect that this would require changes to zero-to-jupyterhub helm charts as well, but from what I can see, there is no way to set the ownerReference using the API provided by this project.

### Alternative options
N/A - Owner references should clearly show the ownership of resources in kubernetes, and as the jupyter-hub is the application responsible for the lifecycle of single user components, it should own those resources.

### Who would use this feature?
It would help render the ownership of the jupyter resources in the argocd view, but it is also best practise to ensure the relationship between resources are known by kubernetes.

The drawback of this, is a deletion of the JupyterHub deployment would force a deletion of all of the single user pods and associated pvc's etc.

### (Optional): Suggest a solution
The [make_pod] function should allow the parameterisation of ownerReference so the resource responsible for creation of the pod can claim ownership of it.

**Comment by consideRatio** [comment]
> N/A - Owner references should clearly show the ownership of resources in kubernetes, and as the jupyter-hub is the application responsible for the lifecycle of single user components, it should own those resources.

Owner references can imply k8s managed garbage collection. We do not wish to garbage collect user pods just because the hub pod is restarted for example, and maybe not even if the hub deployment is recreated. Are you looking to have owner references set for the sake of tracking only, or are you actively wanting garbage collection?

I think for me to support the added complexity about declaring a owner reference, I'd like to see:

1. A documented k8s best-practice or similar to link resources via ownerReference even though one doesn't want to use it for k8s garbage collection.
2. A clear way to not invoke garbage collection, even though a owner reference is set.

**Comment by consideRatio** [comment]
> Cross-namespace owner references are disallowed by design.

I note that if we could set ownerReferences on a pod without ending up with garbage collection issues, we wouldn't be able to do it if kubespawner starts pod in other namespaces.

Read from https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/.

**Comment by consideRatio** [comment]
I'm leaning towards not meddling around with declaring ownerReferences on the kubespawner created resources, it seems like unwanted behavior with garbage collection overall and I didn't quickly learn how to avoid garbage collection and just using it to track what was responsible for its creation.

**Comment by TomHellier** [comment]
More for tracking only, I think the jupyterhub k8s-hub docker container is following the operator pattern, and my usage of operators in the past do typically use CRD to define how they want to operator to work, which isn't strictly what the k8s-hub is doing here.

The resources created by the operators are typically ownerReferenced back up to the CRD, as their lifecycle does depend on the custom resource existing.

I will work on trying to use labels and annotations to help define the relationship between the single-user pods and the hub pod.

My experience with operators are mainly from the following projects, which do ownershipReferences the way I described in the issue, but they do have a CRD to tie back to, whereas the jupyter notebooks don't really have that.

* rook operator - https://rook.io/
* prometheus operator - https://github.com/prometheus-operator/prometheus-operator
* spark operator - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
* redpanda operator - https://github.com/redpanda-data/redpanda/

I've only just started to use jupyterhub so my expectations are probably wrong! :)

**Comment by TomHellier** [comment]
I think I can handle the showing of the resources on the argocd UI, but I need to be able to pass annotations into the pvc created by kubespawner.

I think kubespawner allows you add labels to the storage requested, but it doesn't currently let you add annotations into that list.

[link to where extra_labels can be defined, but no extra_annotations](https://github.com/jupyterhub/kubespawner/blob/9f31d48569025b7bf58dd9bcfe77984cf204c562/kubespawner/spawner.py#L2099)

**Comment by TomHellier** [comment]
I can probably raise a PR to add this in if you'd like @consideRatio

**Comment by consideRatio** [comment]
Ah, JupyterHub as deployed via jupyterhub/zero-to-jupyterhub-k8s does not have a CRD - if that would be the case, i agree that it could make sense that removing a specific CRD resource representing for example a user would make sense. I recognize this pattern from dask/dask-gateway where a CRD is used to define the resource DaskCluster, and then DaskCluster resource will be observed by a "controller" pod that in turn creates various resources owned by the DaskCluster resource. Then, deleting that DaskCluster resource deletes all those owned resources.

Since we don't have a CRD defining a "JupyterHubUserServer" resource or similar, I think we can't go for this by instead coupling user pods to the deploy/hub resource - that is too fragile and not directly representing a user server etc.

---

I think at this point, the discussion about OwnerReferences can be concluded I think. If so, also this issue!

For visibility, if you wish to have another feature to help you with regards to annotations etc, lets switch to another issue. Note that annotations are only set on resource creation for all objects created by KubeSpawner. Some resources, like the PVCs, will stick around for a very long time.

**Comment by consideRatio** [comment]
Quickly - if you see something for labels but not annotations - adding support for annotations would be perfectly fine in my mind! Feel free to go for a PR.
